name: ci
on:
  push:
    paths:
      - react/src/components/**
      - .github/workflows/**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cd react
          echo ${{github.event_path}}
