name: "publish to github packages"
on:
  push:
    branches: [main]
    paths:
      - "src/components/**"
      - "src/index.js"
      - "package.json"
      - ".github/workflows/publish.yml"

jobs:
  prepare:
    uses: Devecorsoft/workflows/.github/workflows/read-version.yml@read-v1
    with:
      platform: "nodejs"
      path: "./package.json"

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install
        run: npm install

      - name: Unit test
        run: npm run test:unit

      - name: e2e test
        run: |
          npm run build
          npm run test:e2e:ci

  verify:
    needs:
      - prepare
      - build
    uses: Devecorsoft/workflows/.github/workflows/verify-version.yml@verify-v1
    with:
      current: ${{ needs.prepare.outputs.version }}
      destination: "git-tag"
  
  publish:
    needs:
      - verify
      - prepare
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm publish
      