name: github packages
on:
  push:
    branches: [main]
    paths:
      - "src/components/**"
      - "src/index.js"
      - "package.json"
      - ".github/workflows/publish.yml"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Read version
        id: read_version
        uses: Devecorsoft/workflows/.github/workflows/read-version-node.yml@v1

      - run: echo "${{ steps.read_version.outputs.version }}"

      