name: github packages
on:
  push:
    branches: [main]
    paths:
      - "src/components/**"
      - "src/index.js"
      - "package.json"
      - ".github/workflows/publish.yml"

jobs:
  prepare:
    uses: Devecorsoft/workflows/.github/workflows/read-version-node.yml@v1
    with:
      package_json: "./package.json"
  publish:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - run: echo "${{ needs.prepare.outputs.version }}"
      